site_name: VkLite - A Modern Vulkan Renderer
docs_dir: docs
site_url: https://rounak-paul.github.io/vklite/
nav:
  - Home: index.md
  - VkLite:
    - 00 Introduction to Vulkan: 
      - Introduction: 00/Introduction.md
    - 01 Project Setup:
      - Vulkan SDK: 01/Vulkan_SDK.md
      - Project Setup: 01/Project_Setup.md
      - Instance Creation: 01/Instance_Creation.md
    # - 02. Renderloop:
    # - 03. The Compute Pipeline:
    # - 04. Immidiate Mode GUI:
    # - 05. GPU Memory:
    # - 06. Graphics Pipeline:
    # - 07. Scene Graph, Transforms and Camera:
    # - 08. Textures and Materials:
    # - 09. Physically Based Rendering:
    
  
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: red
      accent: cyan

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - css/style.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Rounak-Paul/vklite.git
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@rounakpaul001?sub_confirmation=1
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rounakpaul1729/


copyright: |
  &copy; 2025 <a href="https://github.com/Rounak-Paul"  target="_blank" rel="noopener">Rounak Paul</a>
  <br>
  <span style="font-size: 0.9em; color: #888;">
    This site is not affiliated with the Khronos Group. Vulkan® and the Vulkan logo are trademarks of the Khronos Group Inc.
  </span>
